name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=og-sto
            -Dsonar.projectKey=og-sto_gh-repo-clone-Danyah222222-SharedRide-web
            -Dsonar.sources=.
